### ISSUE TITLE
bug in load_data function (line 184 of drizzler.py)

### ISSUE THREAD

**Issue by steigersg** [MazinLab/MKIDPipeline#40]
the 'temp_dir' where the pickle file is dumped to does not default to the scratch directory on dark and causes memory issues

**Comment by steigersg** [comment]
I think there is a similar issue in the write_fits function (line 676) as well

**Comment by RupertDodkins** [comment]
So out of all the variables we have available to us at that namespace none of them contain the tmp parameter. I can default to the location of the h5 files using the MKIDDitheredObservation.obs? Otherwise we'd either have to change config so that MKIDDitheredObservation contained tmp or pass it as an additional argument in drizzler.form() and drizzler.load_data()? Or I can hard code /scratch/tmp in drizzler? 

I think default to the location of the h5 files and create a .tmp folder or something
