### ISSUE TITLE
bug in load_data function of drizzler

### ISSUE THREAD

**Issue by steigersg** [MazinLab/MKIDPipeline#52]
File "/home/steigersg/src/mkidpipeline/mkidpipeline/imaging/drizzler.py", line 190, in load_data
    tempdir = mkidpipeline.config.config.paths.tmp
  File "/home/steigersg/src/mkidcore/mkidcore/config.py", line 165, in __getattr__
    return self[k1][krest] if krest else self[k1]
KeyError: 'tmp'

Beginning in line 189 of drizzler - if a tmp directory is not specified in load_data it throws the above error. Can be worked around in the meantime by just specifying a tmp directory

**Comment by baileyji** [comment]
the temp directory is configured by the pipeline in config.paths

**Comment by RupertDodkins** [comment]
At the moment it says '(optional)' in pipe.yml. So I guess just remove that description and then the code is consistent?

**Comment by baileyji** [comment]
I think the root of this issue is that load_data isn't respecting the pipeline environment paths. If drizzle requires a temp directory then indeed the two options are either to make it non-optional (implies changing code outside of drizzler) or making drizzler run (possibly slower) without temp storage if none is set, seems like the latter is more appropriate here without first reviewing WHY it is flagged as optional. Drizzler must conform to the pipeline, not the other way around.
